name: Daily Caspio Sync

on:
  workflow_dispatch:
  schedule:
    - cron:  '55 13 * * *'   # 01:00 Asia/Bangkok hằng ngày (UTC+7 = 18h UTC hôm trước)

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID:     ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      DEPLOY_URL:    ${{ secrets.DEPLOY_URL }}
      TABLE_NAME:    ${{ secrets.TABLE_NAME }}
      MAX_RECORDS:   ${{ secrets.MAX_RECORDS }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run caspio sync
        run: python src/main.py
